# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "prod-test-shopman"
client_id = "REPLACE"
application_url = "https://eyes-realtor-donations-lebanon.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://eyes-realtor-donations-lebanon.trycloudflare.com/auth/callback",
  "https://eyes-realtor-donations-lebanon.trycloudflare.com/auth/shopify/callback",
  "https://eyes-realtor-donations-lebanon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
