name: Prepare
description: Prepares environment before release and deploy
inputs:
  pat-token:
    required: true
    type: string
    dedscription: Token for accessing github

runs:
  using: "composite"
  steps:
    - name: Checkout code from repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
        fetch-depth: 0
        token: ${{ inputs.pat-token }}

    # Install node
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1

    - name: Installing package.json dependencies
      shell: bash
      run: npm i

    - name: install @actions/core and @action/github packages
      shell: bash
      run: npm i @actions/core @actions/github

    - name: Config git globals
      shell: bash
      run: |
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"