name: "Setup Tag"
description: "Manages tag version and repository variables"
inputs:
  tag: # id of input
    description: "Current tag value from repository variable"
    required: true
    default: d0.0.0
outputs:
  tag-version: # id of output
    description: "New tag version for use in the build release"
runs:
  using: "node20"
  main: "action.js"