# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: [opened, synchronize, ready_for_review] 

  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.stage.outputs.result }}
      deploy: ${{ steps.check-revert.outputs.should-deploy }}
    steps:

      - name: Checkout code from repo
        uses: actions/checkout@v4

      - name: install @actions/core and @action/github packages
        shell: bash
        run: |
          npm i @actions/core @actions/github
          echo "${{ github.event.pull_request.head.ref }}"

      - name: Check for reverts
        id: check-revert
        uses: './.github/workflows/actions/check-revert'
        with:
          source: ${{ github.event.pull_request.head.ref }}
          search: "revert"

      - name: Determine build stage
        id: stage
        run: |
          stage="invalid"
          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref_name }}" = "main" ]; then
              stage="main-branch"
          elif [ "${{ github.ref_name }}" != "main" ] && [ "${{ github.ref_name }}" != 'staging' ] && ! ${{ github.event.pull_request.merged }} ; then
              stage="dev-branch"
          fi
          echo "result=$stage" >> $GITHUB_OUTPUT

  deploy-dev:
    needs: setup
    if: needs.setup.outputs.deploy == 'true' && needs.setup.outputs.stage == 'dev-branch'
    uses: './.github/workflows/deploy-dev.yml'
    secrets: inherit
    
  deploy-staging:
    needs: setup
    if: needs.setup.outputs.deploy == 'true' && needs.setup.outputs.stage == 'main-branch'
    uses: './.github/workflows/deploy-staging.yml'
    secrets: inherit

  deploy-production:
    needs: setup
    if: needs.setup.outputs.deploy == 'true' && needs.setup.outputs.stage == 'main-branch'
    uses: './.github/workflows/deploy-production.yml'
    secrets: inherit