name: Perform checks and triggers build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      branch-name:
        required: true
        type: string

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps:
      - name: checking readiness
        id: check
        env:
          isProduction: ${{ inputs.branch-name == 'main' && inputs.target == 'production' && github.event.pull_request.merged == true }}
          isStaging: ${{ inputs.branch-name == 'main' && inputs.target == 'staging' && github.event.pull_request.merged == true }}
          isDevelopment: ${{ inputs.branch-name != 'main' && inputs.target == 'development' && github.event.pull_request.merged == false }}
        run: |
          check=false
          if [["$isProduction" = true || "$isStaging" = true || "$isDevelopment" = true]; then
            check=true
          fi
          echo "check is: $check"
          JSON_STRING=$(node -pe "
            JSON.stringify({
              isProduction: '$isProduction',
              isStaging: '$isStaging',
              isDevelopment: '$isDevelopment',
              check: $check
            });
          ")
          echo "result=$JSON_STRING" >> "$GITHUB_OUTPUT"

  build:
    name: triggering build workflow
    needs: check
    if: ${{ fromJson(needs.check.outputs.result).check }}
    uses: ./.github/workflows/build.yml
    with:
      target: ${{ inputs.target }}
      branch: ${{ inputs.branch-name }}
    secrets: inherit

  deploy:
    name: triggering deployment workflow
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      target: ${{ inputs.target }}
      tag: ${{ needs.build.outputs.tag }}
      branch: ${{ inputs.branch-name }}
    secrets: inherit