name: Deployment

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: Target environment for the build
      tag:
        required: true
        type: string
        description: Github release tag name
    secrets:
      CLIENT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - name: Deploying Shopify extensions on ${{ inputs.target }} app with tag ${{ inputs.tag }}
        run: |
          npm run deploy \
          -- --version ${{ inputs.tag }} \
          --client-id ${{ secrets.CLIENT_ID }} \ 
          --message "Deploying first version"  -f