name: Deployment in staging

on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: string
        description: Deployment flag
    secrets:
      CLIENT_ID:
        required: true
        description: Client ID of the Shopify staging app
      PAT_TOKEN:
        required: true
        description: Token required to access Github
      SHOPIFY_CLI_TOKEN:
        required: true
        description: Shopify partners token required for deployment


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:

      - name: Checkout code from repo
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Prepare environment
        uses: './.github/workflows/actions/prepare'

      - name: Triggering build
        shell: bash
        run: npm run build

      - name: Create Github release for staging
        if: ${{ inputs.deploy == 'true' }}
        id: release
        uses: ./.github/workflows/actions/release
        with:
          target: staging
          branch: main
          client-id: ${{ secrets.CLIENT_ID }}
          pat-token: ${{ secrets.PAT_TOKEN }}
        
      - name: Deploy staging on main branch
        if: ${{ inputs.deploy == 'true' }}
        uses: ./.github/workflows/actions/deploy
        with:
          target: staging
          branch: main
          tag: ${{ steps.release.outputs.tag }}
          client-id: ${{ secrets.CLIENT_ID }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          partners-token: ${{ secrets.SHOPIFY_CLI_TOKEN }}
