name: Deployment in development

on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: string
        description: Deployment flag
      branch:
        required: true
        type: string
        description: Name of the branch that triggered the event
    secrets:
      CLIENT_ID:
        required: true
        description: Client ID of the Shopify development app
      PAT_TOKEN:
        required: true
        description: Token required to access Github
      SHOPIFY_CLI_TOKEN:
        required: true
        description: Shopify partners token required for deployment


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:

      - name: Checkout code from repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
          
      - name: Prepare environment
        uses: './.github/workflows/actions/prepare'

      - name: Triggering build
        shell: bash
        run: npm run build

      - name: Create Github release for development
        if: ${{ inputs.deploy == 'true' }}
        id: release
        uses: ./.github/workflows/actions/release
        with:
          target: development
          branch: ${{ inputs.branch }}
          client-id: ${{ secrets.CLIENT_ID }}
          pat-token: ${{ secrets.PAT_TOKEN }}
        
      - name: Deploy development on ${{ inputs.branch }} branch
        if: ${{ inputs.deploy == 'true' }}
        uses: ./.github/workflows/actions/deploy
        with:
          target: development
          branch: ${{ inputs.branch }}
          tag: ${{ steps.release.outputs.tag }}
          client-id: ${{ secrets.CLIENT_ID }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          partners-token: ${{ secrets.SHOPIFY_CLI_TOKEN }}
