name: Deployment in production

on:
  workflow_call:
    secrets:
      CLIENT_ID:
        required: true
        description: Client ID of the Shopify production app
      PAT_TOKEN:
        required: true
        description: Token required to access Github
      SHOPIFY_CLI_TOKEN:
        required: true
        description: Shopify partners token required for deployment


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Checkout code from repo
        uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Prepare environment
        uses: './.github/workflows/actions/prepare'

      - name: Triggering build
        shell: bash
        run: npm run build

      - name: Build production on ${{ github.head_ref || github.ref_name }} branch
        id: release
        uses: ./.github/workflows/actions/release
        with:
          target: production
          branch: main
          client-id: ${{ secrets.CLIENT_ID }}
          pat-token: ${{ secrets.PAT_TOKEN }}
        
      - name: Deploy production on ${{ github.head_ref || github.ref_name }} branch
        uses: ./.github/workflows/actions/deploy
        with:
          target: production
          branch: main
          tag: ${{ steps.release.outputs.tag }}
          client-id: ${{ secrets.CLIENT_ID }}
          pat-token: ${{ secrets.PAT_TOKEN }}
          partners-token: ${{ secrets.SHOPIFY_CLI_TOKEN }}
