name: Deployment

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
        description: Target environment for the build
      tag:
        required: true
        type: string
        description: Github release tag name
      branch:
        required: true
        type: string
        description: Branch that triggered the workflow
    secrets:
      CLIENT_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      # Install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: Installing package.json dependencies
        run: npm i

      - name: Prepare toml for deployment
        shell: bash
        run: |
          touch shopify.app.toml
          cp shopify.app.${{ inputs.target }}.toml shopify.app.toml
          sed -i "s/REPLACE/${{ secrets.CLIENT_ID }}/g" shopify.app.toml
          
      - name: Deploying Shopify extensions on ${{ inputs.target }} app with tag ${{ inputs.tag }}
        run: |
          npm i
          npm run deploy -- --version ${{ inputs.tag }} --message "Deploying first version"  -f

      - name: Clean-up after deploy
        run: rm shopify.app.toml